version: "3"
services:
  app:
    container_name: docker-node-mongo
    restart: always
    build: .
    working_dir: /app
    ports:
      - "8000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
